version: '3.8'

services:
  postgres-order:
    image: postgres:13
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

  postgres-driver:
    image: postgres:13
    environment:
      POSTGRES_DB: driver_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-driver-data:/var/lib/postgresql/data

  eureka-server:
    image: eureka-server:latest
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres-order
      - postgres-driver

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres-order

  driver-service:
    image: driver-service:latest
    build:
      context: ./driver-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - postgres-driver

volumes:
  postgres-order-data:
  postgres-driver-data: