server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create


app:
  jwt:
    secret: "your-256-bit-secret-1234567890abcdef1234567890abcdef"
    expirationMs: 86400000 #

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka